<?php
const ADMIN_ROLE_NAME = "Admin";
const ADMIN_ACCESS_LEVEL = 3;

const MODERATOR_ROLE_NAME = "Moderator";
const MODERATOR_ACCESS_LEVEL = 2;

const USER_ROLE_NAME = "User";
const USER_ACCESS_LEVEL = 1;

const UNAUTHORIZED_ACCESS_LEVEL = 0;